title: Altentee
description: The Automation Company
username: altentee
user_description: Altentee Pty Ltd
user_title: alternate entity
email: info@altentee.com
twitter_username: altenteee
github_username:  altenteee
gplus_username:  altenteee

# Google-analytics
google-analytics:
  id: "UA-153490283-2"

exclude: ['package.json', 'src' , 'node_modules']
